name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pint:
    
    runs-on: ubuntu-latest

    steps:

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        tools: composer:v2
        coverage: xdebug

    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Pint Test
      run: |
        composer ci

  
